# Generated by Django 3.1.2 on 2021-12-30 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_name', models.TextField(max_length=255)),
                ('Available_count', models.TextField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumSeats_reserved', models.TextField(max_length=255)),
                ('ResetTime', models.DateTimeField(auto_now_add=True, max_length=255)),
                ('Table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.available')),
            ],
        ),
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumSeats_reserved', models.TextField(max_length=255)),
                ('person', models.TextField(max_length=255)),
                ('Email_address', models.EmailField(max_length=255)),
                ('Table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reserve')),
            ],
        ),
    ]
