# Generated by Django 3.1.2 on 2021-12-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='Available_count',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='available',
            name='Table_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='ResetTime',
            field=models.DateTimeField(auto_now=True, max_length=255),
        ),
    ]
