# Generated by Django 3.1.2 on 2021-12-31 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20211231_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='ResetTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
