# Generated by Django 3.1.2 on 2022-01-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20211231_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm',
            name='Table_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.available'),
        ),
    ]
